trigger:
- main
variables:
- group: my-grp
- name: my-var
  value: 'testing'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Pay-As-You-Go (e5be4f87-0283-49b5-ad1a-f0b2dfeba7a1)'
    KeyVaultName: 'pkmkumar3'
    SecretsFilter: '*'
    RunAsPreJob: false
        pool:
         name: mypool

        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo $(my-var)
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo '$(pkmkumar3) > secret.txt'
                cat secret.txt