# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: mypool
  demands:
  - agent.name -equals az

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'mvn'

- task: Docker@2
  inputs:
    containerRegistry: 'testing1'
    repository: 'test'
    command: 'build'
    Dockerfile: 'dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'testing1'
    repository: 'test'
    command: 'push'