# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
trigger:
- main
stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
         name: mypool
        steps:
        
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo 'Hello world'