trigger:
- main
variables:
- group: my-grp
- name: my-var
  value: 'testing'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
         name: mypool

        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo $(my-var)