trigger:
- main
stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: Build
      displayName: build
      pool:
       name: mypool
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
      - task: Docker@2
        displayName: build
        inputs:
          containerRegistry: 'testing1'
          repository: 'test'
          command: build
          Dockerfile: 'dockerfile'
      - task: Docker@2
        displayName: psuh
        inputs:
          containerRegistry: 'testing1'
          repository: 'test'
          command: 'push'
          Dockerfile: 'dockerfile'
  
          
    