trigger:
- main
variables:
  - group: my-variable-group
  - name: my-passed-variable
    value: $[variables.myhello] # uses runtime expression

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
         name: mypool

        steps:
          - script: echo $(myhello) # uses macro syntax
          - script: echo $(my-passed-variable)
