apiVersion: v1
kind: Service
metadata:
  name:  #{appname}#
spec:
  selector:
    app:  #{appname}#
  type:  LoadBalancer
  ports:
  - protocol: TCP
    port:  80
    targetPort:  #{port}#
    nodePort: 30000
